new update of map
pege22/pege_source_main pull request #41
Opened 2022-09-09 22:24 UTC by 123elsespitia

2022-09-09 22:27 UTC, 123elsespitia commented
luis estoy haciendo muchas porque ya sabes ensayo y error

2022-09-09 23:26 UTC, LUIS9799 commented
Commit en conflicto, crea otra para verificiar los cambios

2022-09-11 01:41 UTC, LUIS9799 requested changes
Won't merge it

2022-09-19 23:58 UTC, LUIS9799 commented
Closed.

2022-09-19 23:58 UTC, closed without merging